# Paths
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/share/python:$PATH
export PATH=/usr/local/share/npm/bin:$PATH
export PATH=/usr/local/share/python:$PATH
export PATH=/usr/local/texlive/2012/bin/x86_64-darwin:$PATH
export PATH=~/.rbenv/bin:$PATH
export PATH=~/bin:$PATH
